number = int(input())
before = str(number - 1)
after = str(number + 1)
print('The next number for the number', str(number), 'is', after + '.')
print('The previous number for the number', str(number), 'is', before + '.')
